---
title: "Supporting information for GCalignR: An R package for aligning Gas-Chromatography data"
author: "Meinolf Ottensmann, Martin A. Stoffel & Joseph I. Hoffman"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prerequisites
```{r}
library(GCalignR)
```
# Single-species alignments



```{r,cache = TRUE}
bbim <- align_chromatograms(data = "data/bbim.txt",
                                   conc_col_name = "Area",
                                   max_diff_peak2mean = 0.02,
                                   min_diff_peak2peak = 0.05,
                                   max_linear_shift = 0.05,
                                   rt_col_name = "RT")
save(bbim, file = "data/bbim_aligned.RData")
```
```{r,cache = TRUE}
beph <- align_chromatograms(data = "data/beph.txt",
                                   conc_col_name = "Area",
                                   max_diff_peak2mean = 0.02,
                                   min_diff_peak2peak = 0.05,
                                   max_linear_shift = 0.05,
                                   rt_col_name = "RT")
save(beph, file = "data/beph_aligned.RData")
```
```{r,cache = TRUE}
bfla <- align_chromatograms(data = "data/bfla.txt",
                                   conc_col_name = "Area",
                                   max_diff_peak2mean = 0.02,
                                   min_diff_peak2peak = 0.05,
                                   max_linear_shift = 0.05,
                                   rt_col_name = "RT")
save(bfla, file = "data/bfla_aligned.RData")
```

